#!/bin/bash
docker cp bigdata:/home/project_docker/res_dpre.csv   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/eda-in-1.txt   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/Models_Result.txt  "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis1.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis2.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis3.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis4.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis5.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis6.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis7.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis8.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis9.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis10.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
docker cp bigdata:/home/project_docker/vis11.png   "C:\\Users\\hagar sliem\\Desktop\\project_docker\\service-result"
